{
  esp0xdeadbeef = {
    site-a = {
      communicationContract = { interfaceTags = { external-nebula = "nebula"; external-wan = "wan"; service-dns-site = "dns-site"; tenant-admin = "admin"; tenant-client = "client"; tenant-mgmt = "mgmt"; }; relations = [ { action = "allow"; from = { kind = "tenant"; name = "admin"; }; id = "allow-admin-to-mgmt-dns"; priority = 100; to = { kind = "service"; name = "dns-site"; }; trafficType = "dns"; } { action = "deny"; from = { kind = "tenant"; name = "client"; }; id = "deny-client-to-mgmt-dns"; priority = 90; to = { kind = "service"; name = "dns-site"; }; trafficType = "dns"; } { action = "allow"; from = { kind = "tenant"; name = "client"; }; id = "allow-client-to-wan-any"; priority = 200; to = { kind = "external"; uplinks = [ "wan" ]; }; trafficType = "any"; } { action = "deny"; from = { kind = "tenant"; name = "client"; }; id = "deny-client-to-mgmt"; priority = 150; to = { kind = "tenant"; name = "mgmt"; }; trafficType = "any"; } { action = "allow"; from = { kind = "tenant"; name = "admin"; }; id = "allow-admin-to-nebula-ssh"; priority = 210; to = { kind = "external"; name = "nebula"; }; trafficType = "ssh"; } { action = "allow"; from = { kind = "external"; name = "nebula"; }; id = "allow-nebula-underlay-to-wan"; priority = 220; to = { kind = "external"; uplinks = [ "wan" ]; }; trafficType = "nebula"; } ]; services = [ { name = "dns-site"; providers = [ ]; trafficType = "dns"; } ]; trafficTypes = [ { match = [ { dports = [ 53 ]; family = "any"; proto = "udp"; } { dports = [ 53 ]; family = "any"; proto = "tcp"; } ]; name = "dns"; } { match = [ { dports = [ 22 ]; family = "any"; proto = "tcp"; } ]; name = "ssh"; } { match = [ { dports = [ 4242 ]; family = "any"; proto = "tcp"; } { dports = [ 4242 ]; family = "any"; proto = "udp"; } ]; name = "nebula"; } ]; };
      ownership = { prefixes = [ { ipv4 = "10.20.10.0/24"; ipv6 = "fd42:dead:beef:10::/64"; kind = "tenant"; name = "mgmt"; } { ipv4 = "10.20.15.0/24"; ipv6 = "fd42:dead:beef:15::/64"; kind = "tenant"; name = "admin"; } { ipv4 = "10.20.20.0/24"; ipv6 = "fd42:dead:beef:20::/64"; kind = "tenant"; name = "client"; } ]; };
      pools = { loopback = { ipv4 = "10.19.0.0/24"; ipv6 = "fd42:dead:beef:1900::/118"; }; p2p = { ipv4 = "10.10.0.0/24"; ipv6 = "fd42:dead:beef:1000::/118"; }; };
      topology = { links = [ [ "s-router-core-wan" "s-router-upstream-selector" ] [ "s-router-core-nebula" "s-router-upstream-selector" ] [ "s-router-upstream-selector" "s-router-policy" ] [ "s-router-policy" "s-router-downstream-selector" ] [ "s-router-downstream-selector" "s-router-access-client" ] [ "s-router-downstream-selector" "s-router-access-admin" ] [ "s-router-downstream-selector" "s-router-access-mgmt" ] ]; nodes = { s-router-access-admin = { attachments = [ { kind = "tenant"; name = "admin"; } ]; role = "access"; }; s-router-access-client = { attachments = [ { kind = "tenant"; name = "client"; } ]; role = "access"; }; s-router-access-mgmt = { attachments = [ { kind = "tenant"; name = "mgmt"; } ]; role = "access"; }; s-router-core-nebula = { role = "core"; uplinks = { nebula = { ipv4 = [ "0.0.0.0/0" ]; ipv6 = [ "::/0" ]; }; }; }; s-router-core-wan = { role = "core"; uplinks = { wan = { ipv4 = [ "0.0.0.0/0" ]; ipv6 = [ "::/0" ]; }; }; }; s-router-downstream-selector = { role = "downstream-selector"; }; s-router-policy = { role = "policy"; }; s-router-upstream-selector = { role = "upstream-selector"; }; }; };
      transport = { overlays = [ { ingressSubject = { kind = "tenant"; name = "admin"; }; mustTraverse = [ "policy" ]; name = "nebula"; terminateOn = "s-router-core-nebula"; } ]; };
    };
  };
}
