{
  esp0xdeadbeef = {
    site-a = {
      communicationContract = { interfaceTags = { external-wan = "wan"; tenant-admin = "admin"; tenant-client = "client"; tenant-mgmt = "mgmt"; }; relations = [{ action = "allow"; from = { kind = "tenant-set"; members = [ "mgmt" "admin" "client" ]; }; id = "allow-tenants-to-wan"; priority = 1; to = { kind = "external"; uplinks = [ "wan" ]; }; trafficType = "any"; } { action = "allow"; from = { kind = "external"; uplinks = [ "wan" ]; }; id = "allow-wan-to-tenants"; priority = 2; to = { kind = "tenant-set"; members = [ "mgmt" "admin" "client" ]; }; trafficType = "any"; }]; services = [ ]; trafficTypes = [{ match = [{ family = "any"; proto = "any"; }]; name = "any"; }]; };
      ownership = { endpoints = [{ kind = "host"; name = "s-sigma"; tenant = "mgmt"; } { kind = "host"; name = "web01"; tenant = "admin"; }]; prefixes = [{ ipv4 = "10.20.10.0/24"; ipv6 = "fd42:dead:beef:10::/64"; kind = "tenant"; name = "mgmt"; } { ipv4 = "10.20.15.0/24"; ipv6 = "fd42:dead:beef:15::/64"; kind = "tenant"; name = "admin"; } { ipv4 = "10.20.20.0/24"; ipv6 = "fd42:dead:beef:20::/64"; kind = "tenant"; name = "client"; }]; };
      pools = { loopback = { ipv4 = "10.19.0.0/24"; ipv6 = "fd42:dead:beef:1900::/118"; }; p2p = { ipv4 = "10.10.0.0/24"; ipv6 = "fd42:dead:beef:1000::/118"; }; };
      topology = { links = [ [ "s-router-core-wan" "s-router-upstream-selector" ] [ "s-router-upstream-selector" "s-router-policy" ] [ "s-router-policy" "s-router-downstream-selector" ] [ "s-router-downstream-selector" "s-router-access-client" ] [ "s-router-downstream-selector" "s-router-access-admin" ] [ "s-router-downstream-selector" "s-router-access-mgmt" ] ]; nodes = { s-router-access-admin = { attachments = [{ kind = "tenant"; name = "admin"; }]; role = "access"; }; s-router-access-client = { attachments = [{ kind = "tenant"; name = "client"; }]; role = "access"; }; s-router-access-mgmt = { attachments = [{ kind = "tenant"; name = "mgmt"; }]; role = "access"; }; s-router-core-wan = { role = "core"; uplinks = { wan = { ipv4 = [ "0.0.0.0/0" ]; ipv6 = [ "::/0" ]; }; }; }; s-router-downstream-selector = { role = "downstream-selector"; }; s-router-policy = { role = "policy"; }; s-router-upstream-selector = { role = "upstream-selector"; }; }; };
    };
  };
}
