{
  esp0xdeadbeef = {
    site-a = {
      communicationContract = { interfaceTags = { external-isp-a = "isp-a"; external-isp-b = "isp-b"; service-site-dns = "site-dns"; tenant-adm = "adm"; tenant-mgmt = "mgmt"; }; relations = [{ action = "allow"; from = { kind = "tenant-set"; members = [ "mgmt" "adm" ]; }; id = "allow-tenants-to-site-dns"; priority = 5; to = { kind = "service"; name = "site-dns"; }; trafficType = "dns"; } { action = "allow"; from = { kind = "tenant-set"; members = [ "mgmt" "adm" ]; }; id = "allow-tenants-to-uplinks"; priority = 100; to = { kind = "external"; uplinks = [ "isp-a" "isp-b" ]; }; trafficType = "any"; }]; services = [{ name = "site-dns"; providers = [ "s-sigma" ]; trafficType = "dns"; }]; trafficTypes = [{ match = [{ dports = [ 53 ]; family = "any"; proto = "udp"; } { dports = [ 53 ]; family = "any"; proto = "tcp"; }]; name = "dns"; }]; };
      ownership = { endpoints = [{ kind = "host"; name = "s-sigma"; tenant = "mgmt"; }]; prefixes = [{ ipv4 = "10.20.10.0/24"; ipv6 = "fd42:dead:beef:20::/64"; kind = "tenant"; name = "mgmt"; } { ipv4 = "10.21.10.0/24"; ipv6 = "fd42:dead:beef:21::/64"; kind = "tenant"; name = "adm"; }]; };
      pools = { loopback = { ipv4 = "10.19.0.0/24"; ipv6 = "fd42:dead:beef:1900::/118"; }; p2p = { ipv4 = "10.10.0.0/24"; ipv6 = "fd42:dead:beef:1000::/118"; }; };
      topology = { links = [ [ "s-router-core-isp-a" "s-router-upstream-selector" ] [ "s-router-core-isp-b" "s-router-upstream-selector" ] [ "s-router-upstream-selector" "s-router-policy" ] [ "s-router-policy" "s-router-downstream-selector" ] [ "s-router-downstream-selector" "s-router-access-adm" ] [ "s-router-downstream-selector" "s-router-access-mgmt" ] ]; nodes = { s-router-access-adm = { attachments = [{ kind = "tenant"; name = "adm"; }]; role = "access"; }; s-router-access-mgmt = { attachments = [{ kind = "tenant"; name = "mgmt"; }]; role = "access"; }; s-router-core-isp-a = { role = "core"; uplinks = { isp-a = { ipv4 = [ "0.0.0.0/0" ]; ipv6 = [ "::/0" ]; }; }; }; s-router-core-isp-b = { role = "core"; uplinks = { isp-b = { ipv4 = [ "0.0.0.0/0" ]; ipv6 = [ "::/0" ]; }; }; }; s-router-downstream-selector = { role = "downstream-selector"; }; s-router-policy = { role = "policy"; }; s-router-upstream-selector = { role = "upstream-selector"; }; }; };
    };
  };
}
