{
  enterprise-a = {
    site-a = {
      communicationContract = { interfaceTags = { external-east-west = "east-west"; tenant-mgmt = "mgmt"; }; relations = [{ action = "allow"; from = { kind = "tenant"; name = "mgmt"; }; id = "allow-mgmt-to-overlay-east-west"; priority = 100; to = { kind = "external"; name = "east-west"; }; trafficType = "any"; } { action = "allow"; from = { kind = "external"; name = "east-west"; }; id = "allow-east-west-underlay-to-isp"; priority = 110; to = { kind = "external"; uplinks = [ "isp" ]; }; trafficType = "nebula"; }]; services = [ ]; trafficTypes = [{ match = [{ dports = [ 4242 ]; family = "any"; proto = "tcp"; } { dports = [ 4242 ]; family = "any"; proto = "udp"; }]; name = "nebula"; }]; };
      ownership = { prefixes = [{ ipv4 = "10.20.10.0/24"; ipv6 = "fd42:dead:beef:10::/64"; kind = "tenant"; name = "mgmt"; }]; };
      pools = { overlay = { ipv4 = { offsetStart = 10; perNodePrefixLength = 32; prefix = "100.64.100.0/24"; }; ipv6 = { offsetStart = 10; perNodePrefixLength = 128; prefix = "fd00:64:100::/64"; }; }; loopback = { ipv4 = "10.19.0.0/24"; ipv6 = "fd42:dead:beef:1900::/118"; }; p2p = { ipv4 = "10.10.0.0/24"; ipv6 = "fd42:dead:beef:1000::/118"; }; };
      topology = { links = [ [ "s-router-core-wan" "s-router-upstream-selector" ] [ "s-router-core-nebula" "s-router-upstream-selector" ] [ "s-router-upstream-selector" "s-router-policy" ] [ "s-router-policy" "s-router-downstream-selector" ] [ "s-router-downstream-selector" "s-router-access" ] ]; nodes = { s-router-access = { attachments = [{ kind = "tenant"; name = "mgmt"; }]; role = "access"; }; s-router-core-nebula = { role = "core"; uplinks = { east-west = { ipv4 = [ "0.0.0.0/0" ]; ipv6 = [ "::/0" ]; }; }; }; s-router-core-wan = { role = "core"; uplinks = { isp = { ipv4 = [ "0.0.0.0/0" ]; ipv6 = [ "::/0" ]; }; }; }; s-router-downstream-selector = { role = "downstream-selector"; }; s-router-policy = { role = "policy"; }; s-router-upstream-selector = { role = "upstream-selector"; }; }; };
      transport = { overlays = [{ mustTraverse = [ "policy" ]; name = "east-west"; peerSite = "enterprise-b.site-b"; terminateOn = "s-router-core-nebula"; }]; };
    };
  };
  enterprise-b = {
    site-b = {
      communicationContract = { interfaceTags = { external-east-west = "east-west"; tenant-mgmt = "mgmt"; }; relations = [{ action = "allow"; from = { kind = "tenant"; name = "mgmt"; }; id = "allow-mgmt-to-overlay-east-west"; priority = 100; to = { kind = "external"; name = "east-west"; }; trafficType = "any"; } { action = "allow"; from = { kind = "external"; name = "east-west"; }; id = "allow-east-west-underlay-to-isp"; priority = 110; to = { kind = "external"; uplinks = [ "isp" ]; }; trafficType = "nebula"; }]; services = [ ]; trafficTypes = [{ match = [{ dports = [ 4242 ]; family = "any"; proto = "tcp"; } { dports = [ 4242 ]; family = "any"; proto = "udp"; }]; name = "nebula"; }]; };
      ownership = { prefixes = [{ ipv4 = "10.30.10.0/24"; ipv6 = "fd42:dead:beef:11::/64"; kind = "tenant"; name = "mgmt"; }]; };
      pools = { overlay = { ipv4 = { offsetStart = 10; perNodePrefixLength = 32; prefix = "100.64.100.0/24"; }; ipv6 = { offsetStart = 10; perNodePrefixLength = 128; prefix = "fd00:64:100::/64"; }; }; loopback = { ipv4 = "10.29.0.0/24"; ipv6 = "fd42:dead:beef:2900::/118"; }; p2p = { ipv4 = "10.11.0.0/24"; ipv6 = "fd42:dead:beef:1100::/118"; }; };
      topology = { links = [ [ "s-router-core-wan" "s-router-upstream-selector" ] [ "s-router-core-nebula" "s-router-upstream-selector" ] [ "s-router-upstream-selector" "s-router-policy" ] [ "s-router-policy" "s-router-downstream-selector" ] [ "s-router-downstream-selector" "s-router-access" ] ]; nodes = { s-router-access = { attachments = [{ kind = "tenant"; name = "mgmt"; }]; role = "access"; }; s-router-core-nebula = { role = "core"; uplinks = { east-west = { ipv4 = [ "0.0.0.0/0" ]; ipv6 = [ "::/0" ]; }; }; }; s-router-core-wan = { role = "core"; uplinks = { isp = { ipv4 = [ "0.0.0.0/0" ]; ipv6 = [ "::/0" ]; }; }; }; s-router-downstream-selector = { role = "downstream-selector"; }; s-router-policy = { role = "policy"; }; s-router-upstream-selector = { role = "upstream-selector"; }; }; };
      transport = { overlays = [{ mustTraverse = [ "policy" ]; name = "east-west"; peerSite = "enterprise-a.site-a"; terminateOn = "s-router-core-nebula"; }]; };
    };
  };
}
